name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  linux:
    name: Build and Test on Linux
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2

      - name: Setup Dependencies
        run: |
          sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y build-essential meson ninja-build

      - name: Setup build with Meson
        run: meson setup build

      - name: Build with Meson
        run: meson compile -C build

      - name: Test with Meson
        run: meson test -C build

  macos:
    name: Build and Test on macOS
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup Dependencies
        run: brew install meson ninja

      - name: Setup build with Meson
        run: meson setup build

      - name: Build with Meson
        run: meson compile -C build

      - name: Test with Meson
        run: meson test -C build

  windows:
    name: Build and Test on Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Dependencies
        run: winget install --id mesonbuild.meson

      - name: Setup build with Meson
        run: meson setup build

      - name: Build with Meson
        run: meson compile -C build

      - name: Test with Meson
        run: meson test -C build

